import type { Metadata } from 'next'
import './globals.css'
import TanstackProvider from '@/components/lib/query/TanstackProvider'
import { Providers } from '@/components/lib/context/Providers'


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang='en'>
      <body>
        <TanstackProvider>
          {/* <Providers> */}
            {children}
          {/* </Providers> */}
        </TanstackProvider>
      </body>
    </html>
  )
}
